config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  resources :flash_sales, only: [:show]

  namespace :admin do
    resources :flash_sales do
      collection do
        get :saleables
      end
      member do
        match 'products', :via => [:get, :post]
      end
    end
  end
end

app/models/spree/flash_sale.rb
class Spree::FlashSale < ActiveRecord::Base
  belongs_to :saleable, polymorphic: true
  has_one :image, as: :viewable, dependent: :destroy, class_name: "Spree::Image"

  validates :name, presence: true
  validates :end_date, presence: true
  validates :start_date, presence: true
  validates :saleable_id, presence: true
  validates :saleable_type, presence: true
  serialize :product_sorting, Array
  # attr_accessible :active, :end_date, :name, :permalink, :start_date, :saleable_id, :saleable_type, :saleable_name, :attachment, :position

  attr_accessor :attachment

  scope :live, lambda { where("start_date <= :start_date AND end_date >= :end_date AND active = :active ", {start_date: DateTime.now.in_time_zone, end_date: DateTime.now.in_time_zone, active: true}) }

  def live?
    return false if !self.active?
    self.start_date.in_time_zone <= DateTime.now.in_time_zone && self.end_date.in_time_zone >= DateTime.now.in_time_zone
  end

  def attachment=(attachment)
    self.image.destroy if self.image.present?
    Spree::Image.create(viewable_type: "Spree::FlashSale", viewable_id: self.id, attachment: attachment)
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def taxon?
    self.saleable_type == "Spree::Taxon"
  end

  def product?
    self.saleable_type == "Spree::Product"
  end

  def saleable_name
    saleable.try(:name)
  end

  def saleable_name=(name)
    self.saleable = self.saleable_type.constantize.find_by_name(name) if name.present?
  end
end

app/controllers/spree/admin/flash_sales_controller.rb
class Spree::Admin::FlashSalesController < Spree::Admin::ResourceController
  def index
    respond_with(@collection) do |format|
      format.html
    end
  end

  def saleables
    search = params[:saleable_type].constantize.search(:name_cont => params[:name])
    render :json => search.result.map(&:name)
  end

  def products
    @search = Spree::FlashSale.ransack(params[:q])
    if request.xhr?
      @flash_sale.update_attributes(:product_sorting => params[:flash_sale][:product_sorting])
      render :json => {:status => :success}, :status => 200
      return
    end
    spree_flash_sales_load_products
  end

  protected

    def location_after_save
      edit_object_url(@object)
    end

    def collection
      return @collection if @collection.present?
      if request.xhr? && params[:q].present?
        @collection = Spree::FlashSale.search params[:q]
      else
        @search = Spree::FlashSale.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_products_per_page])
      end
    end
end

app/controllers/spree/base_controller_decorator.rb
require_dependency 'spree/base_controller'
Spree::BaseController.class_eval do
  def spree_flash_sales_load_products
    @flash_sale                   = Spree::FlashSale.find(params[:id])

    if @flash_sale.saleable_type == "Spree::Taxon"

      if @flash_sale.product_sorting.present?
        @unsorted_products        = @flash_sale.saleable.active_products.find_all_by_id(@flash_sale.product_sorting)

        @flash_sale.saleable.descendants.each do |taxon|
          @unsorted_products += taxon.active_products.find_all_by_id(@flash_sale.product_sorting) # => Products That Already Shorted
        end

        @products                 = @flash_sale.product_sorting.collect {|id| @unsorted_products.detect {|x| x.id == id.to_i} }
        @products.reject!(&:blank?)
        @products                 = @flash_sale.saleable.active_products.find_all_by_id(@flash_sale.product_sorting) if @products.blank?
        @products.uniq!
        @new_products             = []
    
        @flash_sale.saleable.descendants.each do |taxon|
          @new_products += taxon.active_products.where("spree_products.id NOT IN (?)", @flash_sale.product_sorting) # => New Products That Have not been sorted
        end

        @new_products.uniq!
        @new_products = @new_products.sort_by{|v, k| v.created_at}.reverse
      else
        @new_products             = @flash_sale.saleable.active_products

        @flash_sale.saleable.descendants.each do |taxon|
          @new_products += taxon.active_products
        end

        @new_products.uniq!
        @new_products             = @new_products.sort_by{|v, k| v.created_at}.reverse
        @products                 = []
      end
    else
      @products = [@flash_sale.saleable]
    end

  end
end

app/controllers/spree/flash_sales_controller.rb
class Spree::FlashSalesController < Spree::StoreController
  decorates_assigned :flash_sale

  respond_to :html

  def show
    @flash_sale = Spree::FlashSale.find(params[:id])
    spree_flash_sales_load_products
    @products = (@new_products + @products).uniq 
    respond_with(@flash_sale)
  end
end

app/controllers/spree/home_controller_decorator.rb
module Spree
  HomeController.class_eval do
    decorates_assigned :flash_sales # exposes flash_sales in view as helper method

    def index
      @flash_sales = Spree::FlashSale.live.order("position")

      respond_with(@flash_sales)
    end
  end
end

app/views/spree/admin/flash_sales/_form.html.erb
<fieldset data-hook="admin_flash_sale_form_fields">
  <div class="left eight columns alpha" data-hook="admin_flash_sale_form_left">
    <div class='row'>
      <%= form.field_container :name do %>
        <%= form.label :name, raw('Name' + content_tag(:span, ' *', :class => 'required')) %>
        <%= form.text_field :name, :class => 'fullwidth' %>
        <%= form.error_message_on :name %>
      <% end %>
    </div>
    <div class='row'>
      <%= form.field_container :active do %>
        <%= form.label :active, raw('Active' + content_tag(:span, ' *', :class => 'required')) %>
        <%= form.check_box :active %>
        <%= form.error_message_on :active %>
      <% end %>
    </div>
    <div class='row'>
      <%= form.field_container :position do %>
        <%= form.label :position %>
        <%= form.number_field :position %>
        <%= form.error_message_on :position %>
      <% end %>
    </div>
    <div class='row'>
      <% if @flash_sale.image.present? %>
        <%= link_to image_tag(@flash_sale.image.attachment.url(:product), class: 'flash-sale-image'), @flash_sale.image.attachment.url(:original), target: "_blank" %>
      <% end %>
      <%= form.field_container :image do %>
          <%= form.label :image, Spree.t(:upload_image) %><br>
          <% if @flash_sale.new_record? %>
            <p class='hint'>After you create the flash sale you can upload an image.</p>
          <% else %>
            <%= form.file_field :attachment %>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class="right eight columns omega" data-hook="admin_flash_sale_event_form_right">
    <div class="row">
      <div class="alpha four columns">
        <%= form.field_container :start_date do %>
          <%= form.label :start_date, 'Start Date' %>
          <%= form.error_message_on :start_date %>
          <% if @flash_sale.start_date? %>
            <% start_date = l(@flash_sale.start_date, :format => Spree.t('flash_sale.datetimepicker.format')) %>
          <% else %>
            <% start_date = l(Time.zone.now, :format => Spree.t('flash_sale.datetimepicker.format')) %>
          <% end %>
          <%= form.text_field :start_date, :value => start_date, :class => 'timepicker' %>
        <% end %>
      </div>

      <div class="omega four columns">
        <%= form.field_container :end_date do %>
          <%= form.label :end_date, Spree.t('flash_sale.active_record.end_date') %>
          <%= form.error_message_on :end_date %>
          <% end_date = l((@flash_sale.end_date? ? @flash_sale.end_date : Time.zone.now+1.day), :format => Spree.t('flash_sale.datetimepicker.format')) %>
          <%= form.text_field :end_date, :value => end_date, :class => 'timepicker' %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="alpha four columns">
        <%= form.label :saleable, Spree.t('flash_sale.active_record.saleable_type') %>
        <p class='hint'><%= Spree.t('flash_sale.saleable_hint') %></p>
        <%= form.select :saleable_type, [["Product","Spree::Product"], ["Taxon","Spree::Taxon"]], { :include_blank => false }, { :class => 'select2' } %>
        <%= form.error_message_on :saleable_type %>
      </div>

      <div class="omega four columns">
        <%= form.label :saleable_name, Spree.t('flash_sale.active_record.saleable_name') %>
        <p class='hint'><%= Spree.t('flash_sale.saleable_name_hint') %></p>
        <%= form.error_message_on :saleable_id %>
        <%= form.text_field :saleable_name, :class => 'autocomplete', :data => { :auto_complete_url => saleables_admin_flash_sales_url }, :autocomplete => "off" %>
      </div>
    </div>
  </div>
  <div class='clear'></div>
  <p class="form-buttons" data-hook="admin_flash_sale_form_buttons">
    <% if @flash_sale.new_record? %>
      <%= render :partial => 'spree/admin/shared/new_resource_links' %>
    <% else %>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </p>
</fieldset>


<%= javascript_tag do -%>
  var properties = "<%= raw(@properties.to_json) %>";

  $("#flash_sale_saleable_name").on("keydown", function(){
    var saleable_type = $('#flash_sale_saleable_type :selected').val();
    var saleable_name = $('#flash_sale_saleable_name').val();
    var url = $(this).data('auto-complete-url')
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({
        source: url+"?saleable_type="+saleable_type+"&name="+saleable_name
      });
      $(this).focus();
    }
  });
<% end -%>

app/views/spree/admin/flash_sales/edit.html.erb
<% content_for :page_title do %>
  <%= @object.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to 'Edit', [:edit, :admin, @object], :icon => 'icon-wrench' %>
  </li>
<% end %>

<div data-hook="admin_flash_sale_edit_form">
  <%= form_for [:admin, @flash_sale], html: { id: 'flash_sale', multipart: true } do |form| %>
    <%= render partial: 'form', locals: { form: form } %>
  <% end %>
</div>

app/views/spree/admin/flash_sales/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t('flash_sale.title.list') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t('flash_sale.link.new'), new_object_url, :icon => 'icon-plus', :id => 'admin_new_flash_sale_link' %>
  </li>
<% end %>

<table class="index" id="listing_flash_sales" data-hook>
  <colgroup>
    <col style="width: 85%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="admin_flash_sales_index_headers">
      <th><%= sort_link @search, :name, Spree.t(:flash_sale), {}, {:title => 'flash_sales_name'} %></th>
      <th>Position</th>
      <th data-hook="admin_flash_sales_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @flash_sales.each do |flash_sale|%>
      <tr id="<%= spree_dom_id flash_sale %>" data-hook="admin_flash_sales_index_rows" class="<%= cycle('odd', 'even')%> flash-sale">
        <td class='flash_sale_name'><%=link_to flash_sale.name, edit_object_url(flash_sale) %></td>
        <td class='flash_sale_position'>
          <%= form_for [:admin, flash_sale], remote: true do |f| %>
            <%= f.number_field :position %>
          <% end%>
        </td>
        <td><%= link_to "", products_admin_flash_sale_path(flash_sale), class: "icon_link with-tip handle no-text", style: "cursor : pointer;" %></td>

        <td data-hook="admin_flash_sales_index_row_actions" class="actions">
          <%= link_to_edit flash_sale, :no_text => true %>
          <%= link_to_delete flash_sale, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @flash_sales %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
  <div class="box align-center" data-hook="admin_flash_sales_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field">
        <%= f.label Spree.t(:name) %> <br>
        <%= f.text_field :name_cont, :class => 'fullwidth' %>
      </div>
      <div data-hook="admin_users_index_search_buttons">
        <%= button Spree.t(:search), 'icon-search' %>
      </div>
    <% end %>
  </div>
<% end %>


<script type='text/javascript'>
  $(function() {
    $(".edit_flash_sale input").change(function (){
      $(this).closest("form").submit();
    })
  });
</script>

app/views/spree/admin/flash_sales/new.html.erb
<% content_for :page_title do %>
  <%= @flash_sale.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to 'New', [:admin, @flash_sale], :icon => 'icon-arrow-left', :id => 'admin_new_flash_sale__link' %>
  </li>
<% end %>

<div data-hook="admin_flash_sale__edit_form">
  <div id="flash-sale-form-wrapper">
    <%= form_for [:admin, @flash_sale], :html => { :id => 'admin_flash_sale', :multipart => true } do |form| %>
      <%= render partial: 'form', locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/spree/admin/flash_sales/products.html.erb
  <table>
    <thead>
      <tr>
        <td>Position</td>
        <td>Product Name</td>
      </tr>
    </thead>
    <tbody id="sortable">
      <% position_tr = 1 %>
      
      <% @new_products.each do |new_product| %>
        <% sortable_id = "product_sorting_#{new_product.id.to_s}" %>
          <tr class="product_list_new" id="<%= sortable_id.html_safe %>" style="background-color: yellow;cursor:pointer; ">
            <td><%= position_tr %></td>
            <td><%= new_product.name %></td>
          </tr>
        <% position_tr = position_tr + 1 %>
      <% end %>

      <% @products.each do |product| %>  
        <% product_position = @product_sorting[product.id] if @product_sorting.present? %>
          <% sortable_id = "product_sorting_#{product.id.to_s}" %>
          <tr class="product_list" id=<%= sortable_id.html_safe %> style="cursor:pointer;">
            <td><%= position_tr %></td>
            <td><%= product.name %></td>
          </tr>
        <% position_tr = position_tr + 1 %>
      <% end %>
    
    </tbody>
  </table>

app/views/spree/flash_sales/_flash_sale.html.erb
<article class='flash-sale' id="flash_sale_<%= flash_sale.id %>" data-hook="flash-sale" itemscope itemtype='http://schema.org/Offer'>
  <%= flash_sale.render_image %>
  <h1 class='flash-sale-name'>
    <%= link_to flash_sale.name, flash_sale.render_url, itemprop: 'name', title: flash_sale.name %>
  </h1>
  <div class='flash-sale-expires'>
    Gone in: <span class='flash-sale-countdown' data-countdown="<%= flash_sale.countdown_format %>" data-layout="<%= flash_sale.countdown_layout %>"></span>
  </div>
</article>

app/views/spree/flash_sales/_image.html.erb
<%= link_to image_tag(flash_sale.image.attachment.url(:product), class: 'flash-sale-image'), flash_sale.render_url, itemprop: 'url' %>

app/views/spree/flash_sales/show.html.erb
<article class='flash-sale-page'>
  <h1 class='flash-sale-name'>
    <%= @flash_sale.name %>
  </h1>
  <div class='flash-sale-expires'>
    Gone in: <span class='flash-sale-countdown' data-countdown="<%= flash_sale.countdown_format %>" data-layout="<%= flash_sale.countdown_layout %>"></span>
  </div>
  <div class='flash-sale-products'>
    <%= render :partial => 'spree/shared/products', :locals => { :products => @products } %>
  </div>
  <%- if @products.blank? %>
    <p class='notice'>There doesn't seem to be any products available for this sale anymore...</p>
  <% end %>
</article>